"""縦横連結アダプターラックv2の寸法の正本。単位mm。"""

INPUTS = [
    ("AdapterWidth", "99.05 mm", "電源の送風方向寸法、公開実測値"),
    ("AdapterLength", "98.99 mm", "ACとUSB-Cを結ぶ方向の寸法、公開実測値"),
    ("AdapterHeight", "35.17 mm", "電源の厚さ、公開実測値"),
    ("FrameThickness", "12 mm", "側枠の厚さ"),
    ("InnerWidth", "140 mm", "左右側枠の内側距離"),
    ("FrameDepth", "148 mm", "側枠の奥行"),
    ("ModuleHeight", "76 mm", "1段の高さ、上下は柱面で接触"),
    ("BaseHeight", "20 mm", "側枠の下梁の高さ"),
    ("TopBeam", "10 mm", "側枠の上梁の高さ"),
    ("PostDepth", "14 mm", "前後の柱の奥行"),
    ("BeamWidth", "12 mm", "電源を支える棒の幅"),
    ("BeamHeight", "8 mm", "支持棒の厚さ"),
    ("BeamPitch", "68 mm", "前後の支持棒の中心距離"),
    ("TenonLength", "8 mm", "支持棒の差込長さ"),
    ("FitClearance", "0.3 mm", "新設接合部の片側隙間、試験片で選定"),
    ("SideGap", "1.5 mm", "電源と支持棒の横ずれ止めの隙間"),
    ("LipWidth", "3 mm", "横ずれ止め幅"),
    ("LipHeight", "4 mm", "横ずれ止め高さ"),
    ("PinDiameter", "4 mm", "支持棒固定ピン径"),
    ("PinHeadDiameter", "8 mm", "固定ピン頭径"),
    ("PinHeadHeight", "3 mm", "固定ピン頭厚さ"),
    ("StackDiameter", "6 mm", "上下位置決めピン径"),
    ("StackEngagement", "9 mm", "上下それぞれの差込長さ"),
    ("ColumnGap", "12 mm", "横に並べる側枠間の隙間"),
    ("JoinY", "50 mm", "横連結の前後位置"),
    ("JoinPegDiameter", "4 mm", "横連結ピン径"),
    ("JoinEngagement", "8 mm", "横連結ピンの差込長さ"),
    ("JoinThickness", "4 mm", "横連結の橋の厚さ"),
    ("BoltHole", "4.5 mm", "M4通し穴、実物金具で確認"),
    ("StrapPitch", "14 mm", "上下保持板のボルト穴間隔"),
    ("StrapThickness", "3 mm", "上下保持板の厚さ"),
    ("FanSize", "120 mm", "NF-A12x25 G2の外形"),
    ("FanThickness", "27 mm", "防振パッド込みの厚さ"),
    ("FanHolePitch", "105 mm", "ファン取付穴の中心距離"),
    ("FanOpening", "114 mm", "送風用開口径"),
    ("FanPlateThickness", "4 mm", "ファン保持板の厚さ"),
    ("FanMargin", "12 mm", "前面枠の上下余白。縦2段の外形に対して上下4mm内側"),
    ("FanMountLow", "16 mm", "保持板の下側ボルト高さ"),
    ("FanMountHigh", "60 mm", "保持板の上側ボルト高さ"),
    ("AccessoryPitch", "28 mm", "ファンコン取り付け面用M4穴間隔"),
    ("AccessoryThickness", "11 mm", "共通ケースドック8mm＋一体スペーサー3mm"),
    ("CableAllowance", "30 mm", "左右各端の配線用設計余白"),
]
DERIVED = [
    ("ModuleWidth", "=InnerWidth + 2 * FrameThickness", "1台分の幅"),
    ("ColumnPitch", "=ModuleWidth + ColumnGap", "横増設の中心距離"),
    ("PostX", "=InnerWidth / 2 + FrameThickness / 2", "左右側枠の中心"),
    ("PostY", "=FrameDepth / 2 - PostDepth / 2", "前後柱の中心"),
    ("BeamLength", "=InnerWidth + 2 * TenonLength", "支持棒全長"),
    ("BeamZ", "=BaseHeight - BeamHeight", "支持棒底面高さ"),
    ("PinX", "=InnerWidth / 2 + TenonLength / 2", "支持棒固定ピンの左右位置"),
    ("FanCenterZ", "=ModuleHeight", "縦2段の境界にファン中心を配置"),
    ("FanPlateBottom", "=FanCenterZ - FanSize / 2 - FanMargin", "ファン保持板下端"),
    ("FanPlateHeight", "=FanSize + 2 * FanMargin", "ファン保持板高さ"),
    ("JoinSpacing", "=ColumnPitch - 2 * PostX", "横連結ピンの中心距離"),
    ("JoinWidth", "=JoinSpacing + 16 mm", "横連結の橋の幅"),
]
CELLS = {name: f"B{row}" for row, (name, _, _) in enumerate(INPUTS + DERIVED, 2)}
